### ISSUE TITLE
thirdparty protobuf compile fail

### ISSUE THREAD

**Issue by HenryQin** [chen3feng/blade-build#1015]
cd thirdparty
blade build :protobuf
then we get these error message 

thirdparty/protobuf/BUILD:3: error: protobuf: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
thirdparty/protobuf/BUILD:8: error: protoc: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
thirdparty/protobuf-2.4.1/src/BUILD:42: error: protobuf: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
thirdparty/protobuf-2.4.1/src/BUILD:84: error: protoc: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
thirdparty/glog/BUILD:3: error: glog: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
thirdparty/glog-0.3.2/src/BUILD:19: error: glog: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
thirdparty/gflags/BUILD:3: error: gflags: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
thirdparty/gflags-2.0/src/BUILD:10: error: gflags: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])

**Comment by noanswer** [comment]
*The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])*

Fix your BUILD as tips above.

**Comment by noanswer** [comment]
> cd thirdparty blade build :protobuf then we get these error message
> 
> thirdparty/protobuf/BUILD:3: error: protobuf: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = []) thirdparty/protobuf/BUILD:8: error: protoc: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = []) thirdparty/protobuf-2.4.1/src/BUILD:42: error: protobuf: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = []) thirdparty/protobuf-2.4.1/src/BUILD:84: error: protoc: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = []) thirdparty/glog/BUILD:3: error: glog: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = []) thirdparty/glog-0.3.2/src/BUILD:19: error: glog: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = []) thirdparty/gflags/BUILD:3: error: gflags: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = []) thirdparty/gflags-2.0/src/BUILD:10: error: gflags: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])

The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])

Fix your BUILD as tips above.

**Comment by chen3feng** [comment]
Yes, it should works
