### ISSUE TITLE
请问一下应该怎样使用blade的install辅助功能，有没有代码示例呢

### ISSUE THREAD

**Issue by Numblzw** [chen3feng/blade-build#1028]
https://github.com/chen3feng/blade-build/blob/master/doc/zh_CN/misc.md#install
尝试过使用 blade install报错如下
usage: blade [-h] [--version] {build,run,test,clean,query,dump} ...
blade: error: argument command: invalid choice: 'install' (choose from 'build', 'run', 'test', 'clean', 'query', 'dump')

**Comment by chen3feng** [comment]
Blade has no `install` sub command, there is a standalone install script, will install a symbolic link to your home `~/bin/`, just run:
```bash
./install
```
