### ISSUE TITLE
inclusion check will still be triggered in a second blade build

### ISSUE THREAD

**Issue by noanswer** [chen3feng/blade-build#1034]
**Describe the bug**

Building the same target in a second time expects full-use the build64_release cache.
Bug the inclusion-check runs again.

**To Reproduce**
1. Go to directory: `cd example and rm -rf build64_release`
2. Run `blade build common`
3. Run `blade build common` again.
![blade-build](https://github.com/chen3feng/blade-build/assets/4657796/c9135c1d-1627-482f-b991-5e50981e0f82)

**Expected behavior**
Hope that inclusion-check will run exactly in the first time and won't update and run in a second time when codes are the same.

**Error message**
After adding some logs, header deps has been updated after first build.

**Comment by chen3feng** [comment]
Will see it at weekend.

**Comment by chen3feng** [comment]
fixed
