### ISSUE TITLE
用blade build编译时的默认并发度可以在BLADE_ROOT文件里面设置吗？

### ISSUE THREAD

**Issue by Numblzw** [chen3feng/blade-build#1041]
在blade build的时候如果不设置-j 4，默认构建的并发度是多少。默认的并发度可以在BLADE_ROOT文件里面设置吗？

**Comment by chen3feng** [comment]
默认是根据机器配置计算的。可以在[配置文件](https://github.com/chen3feng/blade-build/blob/master/doc/zh_CN/config.md#global_config)里修改。
`BLADE_ROOT` 也是个配置文件，但是不建议在里面设置，因为不同的机器配置未必相同。
