### ISSUE TITLE
是否可以关闭掉hdrs强检查，回归到最开始的版本

### ISSUE THREAD

**Issue by anqin** [chen3feng/blade-build#1044]
typhoon-blade最早版本是没有hdrs这个要求的。这在引入三方库的时候很方便，现在加了这个后，prebuilt的库还得配置一下，各种路径经常难以对齐。

**Comment by chen3feng** [comment]
https://github.com/chen3feng/blade-build/blob/master/doc/zh_CN/build_rules/cc.md#%E4%BF%AE%E5%A4%8D-hdrs-%E5%BC%95%E5%8F%91%E7%9A%84%E4%BE%9D%E8%B5%96%E7%BC%BA%E5%A4%B1%E7%9A%84%E6%A3%80%E6%9F%A5%E9%97%AE%E9%A2%98
