### ISSUE TITLE
--generate-dynamic has bug for deps missing detection

### ISSUE THREAD

**Issue by yeshunping** [chen3feng/blade-build#23]
--generate-dynamic has bug for deps missing detection, 
I has a library, which using snappy, but I don't deps on snappy,  But
blade build util/... --generate-dynamic
No errors were reported.

We know a solution for it, for example
cc_library(name = "bar",
                  desp = [":foo1",
                               "foo2",
                               ],
)

we can fake a cc_binary using 
g++ -o bar_dep_check_dummy  -Wl,--whole-archive -lbar -Wl,--no-whole-archive xxx/libmain.a libfoo1.a  libfoo2.a 

NOTE:
xxx/libmain.a  is a library, it has a empty main function, but do NOTHING at all.
We whole-archive target library, so if it miss any library, linking error will be reported.

I try to implement this feature, but it's a little hard for me now.

**Comment by chen3feng** [comment]
fixed long time ago
