### ISSUE TITLE
Build path embedded when linking shared libraries without SONAME

### ISSUE THREAD

**Issue by jimmystlr** [chen3feng/blade-build#327]
When linking to a shared library without SONAME, it will embed the build path as the linked name, eg.

build64_release/xxx/libmkl_intel_lp64.so => not found
build64_release/xxx/libmkl_sequential.so => not found
build64_release/xxx/libmkl_core.so => not found
build64_release/xxx/libmkl_avx2.so => not found
build64_release/xxx/libmkl_def.so => not found

It is caused by the linking mode of blade, which links to a shared library by directly using its path "build64_release/xxx/libyyy.so" but not the way "-Lbuild64_release/xxx -lyyy".

**Comment by chen3feng** [comment]
embed path into the path is the feasible way to avoid namesake in different dirs, can we have a better choice? 
maybe we can stop embedding its path into binary for prebuilt shared libraries?

**Comment by jimmystlr** [comment]
Depends on if to avoid namesake in different dirs is a real requirement, especially for those linking different libraries with the same name into one target? IMO, it's not the common case.

**Comment by chen3feng** [comment]
It's really a problem in a large code base. for example, in our internal project, and most tests are dynamic-linked to save the disk space.
The dynamic-linked cc_library are designed to be used locally only in developing environments. We strongly suggest that only deploy the static linked executables to the production system. If you need a dynamic-linked library to be used as an extension in the other programming languages or dlopen it at runtime, you should use the `cc_plugin` rule.
Temporarily close this issue. we will reopen it if there is a better solution.

**Comment by jimmystlr** [comment]
Get it, thx for the reply
