### ISSUE TITLE
per-folder warning check during compilation

### ISSUE THREAD

**Issue by lianglia-apollo** [chen3feng/blade-build#473]
We want to only check warnings for some folders but not for other folders. Is there a way to set this in blade? I know that bazel can do this by using the build --per_file_copt option.

**Comment by zhuangli1987** [comment]
@chen3feng I have the same problem. When I compile the code with some thirdparty dependencys. The warning options （-wall -werror）defined in my code also effect the code in thidparty. Which means， I have to fix all issues out of my work scope. Is there any possible to have a option to let compiler knows not to check dependency's code style.

**Comment by chen3feng** [comment]
Planning to support this feature

**Comment by chen3feng** [comment]
> @chen3feng I have the same problem. When I compile the code with some thirdparty dependencys. The warning options （-wall -werror）defined in my code also effect the code in thirdparty. Which means， I have to fix all issues out of my work scope. Is there any possible to have a option to let compiler knows not to check dependency's code style.

You can use `warning='no'` attribute to suppress warnings
