### ISSUE TITLE
如何依赖`gen_rule`生成的 `.a` 库？

### ISSUE THREAD

**Issue by reyoung1110** [chen3feng/blade-build#481]
我想使用golang和C++混合编程，使用C++调用Go中的函数。看到了`gen_rule`的功能。

我写了,

```
gen_rule(
    name='add',
    srcs=["add.go"]
    cmd="go build  -buildmode=c-archive add.go",
    outs=["add.a", "add.h"]
)
```

但这个`add.a`如何被其他的`cc_binary`或者`cc_library`依赖呢？

**Comment by chen3feng** [comment]
现在好像还不支持，只能先用prebuilt的cc_library顶着。
考虑引入
gen_rule(
    name='add',
    srcs=["add.go"]
    cmd="go build  -buildmode=c-archive add.go",
    outs=["add.a", "add.h"],
    outs_type = 'cc_library',
)
之类的来解决

**Comment by chen3feng** [comment]
已经支持，通过 foreign_cc_library，这部分代码已经在 master 中，内部试用中，尚待完善。
