### ISSUE TITLE
动态链接库的路径依赖

### ISSUE THREAD

**Issue by AdolHong** [chen3feng/blade-build#520]
尝试用cc_library生成了一个动态链接库，并用binary去调用。

结果，可执行文件对动态库有一个依赖路径，如下：
./dynamic: error while loading shared libraries: build64_release/Projects/Content/Plugin/Src/dynamic_demo/libeigen.so

我想请教一下，怎么修改这个路径依赖。
难道，我得建build64_release/Projects/Content/Plugin/Src/dynamic_demo/ 这一串文件夹？

**Comment by chen3feng** [comment]
Blade的dynamic_library生成是为了满足动态链接的单元测试等用途，不太适合用来不熟。通常我们都是部署静态链接的可执行文件。blade链接动态库时带上路径是为了避免不同路径下动态库可能重名的冲突。
在确实需要生成供运行期间的动态加载的动态库的需求，比如jni，python C扩展等，我们用[cc_plugin](../blob/master/doc/zh_CN/build_rules/cc.md#cc_plugin)规则来支持。

**Comment by chizhu** [comment]
> 尝试用cc_library生成了一个动态链接库，并用binary去调用。
> 
> 结果，可执行文件对动态库有一个依赖路径，如下：
> ./dynamic: error while loading shared libraries: build64_release/Projects/Content/Plugin/Src/dynamic_demo/libeigen.so
> 
> 我想请教一下，怎么修改这个路径依赖。
> 难道，我得建build64_release/Projects/Content/Plugin/Src/dynamic_demo/ 这一串文件夹？

我现在也遇到一样的问题，请问您后来怎么解决的

**Comment by chen3feng** [comment]
用 cc_plugin

Zhimin Lin <notifications@github.com> 于2020年6月7日周日 下午4:57写道：
