### ISSUE TITLE
not support protobuf.3.6.0 compiling flag -std=c++11

### ISSUE THREAD

**Issue by yuhuichina** [chen3feng/blade-build#536]
need upgrade to protobuf.3.6.0 when using tensorflow 1.12 lib, or will report error.
but protobuf.3.6.0 need compiling flag std=c++11, our blade system do not support proto_library_config param such as protobuf_extra_cppflags = ['-std=c++11']

**Comment by WNTDJMHH** [comment]
The same question how to support  c++11 in proto_library_config

**Comment by yuhuichina** [comment]
> The same question how to support c++11 in proto_library_config

I have commit a pull request to fix this, but not accepted right now

**Comment by chen3feng** [comment]
Thank you for your push, I was too busy to see it, sorry for late.
