### ISSUE TITLE
blade test 无法传入外部的gtest 参数

### ISSUE THREAD

**Issue by markshao** [chen3feng/blade-build#541]
希望可以传入一些 gtest 的命令行参数 ，例如
`Test Output:
  --gtest_color=(yes|no|auto)
      Enable/disable colored output. The default is auto.
  --gtest_print_time=0
      Don't print the elapsed time of each test.
  --gtest_output=(json|xml)[:DIRECTORY_PATH/|:FILE_PATH]
      Generate a JSON or XML report in the given directory or with the given
      file name. FILE_PATH defaults to test_details.xml.
  --gtest_stream_result_to=HOST:PORT
      Stream test results to the given server.
`

#1 尝试过用 --testargs "--gtest_output json" 的方式，不work
#2 尝试在 BUILD中，通过配置testdata的方式 ，也不行
`testdata = [
    ('--gtest_output', 'xml')
]`

**Comment by WindLeeWT** [comment]
testargs 改为 unix style 的 -- ，example_test 是一个 cc_test 目标：

`blade test :example_test -- --gtest_repeat=20 --gtest_break_on_failure`

**Comment by markshao** [comment]
还是不行

如果直接用 test 的binary 是可以生成 test_detail.json的
`./xxx_test --gtest_output=json`

但是用你的例子，是无法生成的
`blade test -- --gtest_output=json`

**Comment by markshao** [comment]
@WindLeeWT

**Comment by WindLeeWT** [comment]
看一下你用的 blade 的版本，另外在运行 ut 时有没有类似如下的输出：

![20190522102712](https://user-images.githubusercontent.com/14238472/58143098-2fb9b780-7c7c-11e9-9e16-bc49692bddb7.png)

**Comment by markshao** [comment]
`blade --version` 好像不行，看了一下 ChangeLog, 应该是一个比较老的版本

`2013-05-25  Tencent Inc. <chen3feng@gmail.com>

	* Add cc_config:optimize config option, see blade.conf
.....
`

UT 的执行是有类似输出的

![Lark20190522192034](https://user-images.githubusercontent.com/1078081/58170787-02dec200-7cc7-11e9-89a9-505623d55b92.png)

**Comment by WindLeeWT** [comment]
13 年的距离有点远了，之后代码变动比较大，用新的版本试试吧
