### ISSUE TITLE
Build error when upgraded gcc9.1 on centos6.8

### ISSUE THREAD

**Issue by raymondzuo** [chen3feng/blade-build#555]
With using blade-build system and gcc4.8.2, my project was built success. But when I upgraded gcc to version 9.1, some errors occurs like: [ error: 'function' in namespace 'std' does not name a template type ] , [ error: 'std::placeholders' has not been declared ], [ error: 'bind' is not a member of 'std' ].

**Comment by WindLeeWT** [comment]
Make sure that you include the correct header:
```c++
#include <functional>
```
Also, check the compiler options `cxxflags` if there is `-std=c++11` since `std::function` and `std::bind` come with C++11. It would be even better with c++14/17 if you have been upgraded to gcc-9.1 already.

**Comment by raymondzuo** [comment]
> compiler

WindLeeWT, thanks! It works!

**Comment by raymondzuo** [comment]
> Make sure that you include the correct header:
> 
> ```c++
> #include <functional>
> ```
> 
> Also, check the compiler options `cxxflags` if there is `-std=c++11` since `std::function` and `std::bind` come with C++11. It would be even better with c++14/17 if you have been upgraded to gcc-9.1 already.

WindLeeWT, thanks! It works!

**Comment by raymondzuo** [comment]
When resolve the previous errors, i got an new error: [ cc1plus: error: thirdparty: No such file or directory [-Werror=missing-include-dirs] ]. @WindLeeWT , could you please give me an advice to resolve this error?

**Comment by WindLeeWT** [comment]
I assume you have imported `blade.conf` automatically and added `thirdparty` into `extra_incs` of cc_config, just create a directory inside the workspace root(the directory where BLADE_ROOT belongs to):
```bash
mkdir thirdparty
```
Btw, please see doc folder for more details about the recommended directory layout.

**Comment by raymondzuo** [comment]
> I assume you have imported `blade.conf` automatically and added `thirdparty` into `extra_incs` of cc_config, just create a directory inside the workspace root(the directory where BLADE_ROOT belongs to):
> 
> ```shell
> mkdir thirdparty
> ```
> 
> Btw, please see doc folder for more details about the recommended directory layout.

ok, thank you.
