### ISSUE TITLE
Implicit dependency not found

### ISSUE THREAD

**Issue by pikez** [chen3feng/blade-build#559]
When we modified BUILD file and using incremental compile build. Blade report an error said `Implicit dependency  xxxx not found. needed by target 'xxxxx.h'`.
What does it mean？How we can avoid it? Thanks

**Comment by WindLeeWT** [comment]
I assume you're still building with `scons` as the underlying build engine which blade is on top of, blade enables the implicit dependency caching of scons by default which could be disabled with the following command line option according to your version of blade:

- --scons-options='--implicit-deps-changed'

- --native-builder-options='--implicit-deps-changed'

See [Caching Implicit Dependencies](https://scons.org/doc/production/HTML/scons-user.html#idm1153) for more details on this caching mechanism of `scons`

FYI, we're on the way switching `scons` to `ninja` underneath and `scons` is likely to be deprecated in the near future.

**Comment by pikez** [comment]
Thanks a million! We'll have a try
