### ISSUE TITLE
Build error with gcc8 on Mac OS

### ISSUE THREAD

**Issue by JedHong** [chen3feng/blade-build#564]
We found that the the build command of g++-8 took '-Iwithsysroot' as default, which worked with gcc4.8.2 but failed with gcc8, like:

cc1plus: error: withsysroot: No such file or directory [-Werror=missing-include-dirs] 

We could not find this setting in blade conf files. How can I remove this '-Iwithsysroot' option?

**Comment by WindLeeWT** [comment]
I'm not aware of this option in blade, check `blade.conf` and `BLADE_ROOT` if there is any clue of `-Iwithsysroot`. Futhermore, let me know your blade version and even if the backend builder is scons, I don't believe that scons adds this option automatically on mac.

**Comment by JedHong** [comment]
We didn't get any clue in blade.conf or BLADE_ROOT. Things happened even though with the examples of blade. We use the blade with 1.1.2 and scons 3.1.1 as backends. Tks!

**Comment by WindLeeWT** [comment]
Run the following command with a simple project and let me take a look at the generated `SConstruct` within the same folder as BLADE_ROOT
```bash
blade build --generate-scons-only :your_target_name
```

**Comment by JedHong** [comment]
Yah！Caught it！

if not os.path.exists('build64_release'):
    os.mkdir('build64_release')
console.set_log_file("build64_release/blade_scons.log")
top_env = scons_helper.make_top_env("build64_release")
scons_helper.setup_compliation_verbose(top_env, color_enabled=True, verbose=False)
time_value = Value("Wed Sep 11 23:52:10 2019")
scons_helper.setup_proto_builders(top_env, "build64_release", protoc_bin="protoc", protoc_java_bin="protoc", protobuf_path="thirdparty", protobuf_incs_str="", protobuf_php_path="thirdparty/Protobuf-PHP/library", protoc_php_plugin="thirdparty/Protobuf-PHP/protoc-gen-php.php", protoc_go_plugin="")
scons_helper.setup_thrift_builders(top_env, build_dir="build64_release", thrift_bin="thrift", thrift_incs_str="")
scons_helper.setup_fbthrift_builders(top_env, "build64_release", fbthrift1_bin="fbthrift/compiler/thrift1", fbthrift2_bin="fbthrift/compiler/thrift2", fbthrift_incs_str="")
scons_helper.setup_cuda_builders(top_env, "nvcc", "")
scons_helper.setup_swig_builders(top_env, "build64_release")
scons_helper.setup_java_builders(top_env, "", "")
scons_helper.setup_scala_builders(top_env, "")
scons_helper.setup_go_builders(top_env, "", "")
scons_helper.setup_other_builders(top_env)
t**op_env.Replace(CC="gcc", CXX="g++", SECURECXX="None g++", CPPPATH=["", "build64_release", "withsysroot"], CPPFLAGS=['-DHAVE_CONFIG_H', '-D_GLIBCXX_USE_CXX11_ABI=0', '-m64', '-mcx16', '-pipe', '-g', '-DNDEBUG', '-D_FILE_OFFSET_BITS=64', '-D__STDC_CONSTANT_MACROS', '-D__STDC_FORMAT_MACROS', '-D__STDC_LIMIT_MACROS'], CFLAGS=[], CXXFLAGS=[], LINK="g++", LINKFLAGS=['-m64'])**
top_env.Replace(ARFLAGS="rcs")
top_env.Replace(RANLIBCOM="", RANLIBCOMSTR="")
top_env.Replace(ASFLAGS=["-g", "--64"])
top_env.Replace(ASPPFLAGS="-Wa,--64")
env_with_error = top_env.Clone()
env_no_warning = top_env.Clone()

Why we have the guy here?

**Comment by JedHong** [comment]
Python is installed by default on my Mac, and the output of "python-config --includes" is like:

-iwithsysroot /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7

Any way to drop it from the CPPPATH?

**Comment by WindLeeWT** [comment]
First, there is little difference on options of gcc between macOS and centOS. Internally blade is mostly well tested on centOS on which the corresponding option to `-iwithsysroot` I believe is the `-isysroot` according to the [online manual](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Directory-Options.html):

    --sysroot=dir
    Use dir as the logical root directory for headers and libraries. For example, if the compiler normally 
    searches for headers in /usr/include and libraries in /usr/lib, it instead searches dir/usr/include and 
    dir/usr/lib.

    If you use both this option and the -isysroot option, then the --sysroot option applies to libraries, 
    but the -isysroot option applies to header files.

On my centOS dev machine, `python-config --includes` outputs:
```bash
-I/usr/include/python2.6 -I/usr/include/python2.6
```

Second, when using `scons` as the underlying build engine(which is the default), blade automatically fetch python header directory as seen here and add it to the global header search path for c/c++ targets accordingly. It seems unreasonable for me to do this and this has no effect given 95% percent of time the user doesn't care about this python directory when developing on c/c++ projects. There might be some historic reasons @chen3feng could known about.

The only possible case is for python extension development. However, it's likely to have some mismatch between the python versions, such as, blade is using python2.7 while the user is working on python3.7 extension. As a result, python include directory should be an option set explicitly when really needed, but not set by default in blade.

Finally, I remove this auto detect python include directory when working on `ninja` which you could have a try.

**Comment by JedHong** [comment]
Sure, it seems ninja would be a good choice now. We will also try to remove this auto detection on local repo. Thanks Wenting!

**Comment by gitclem** [comment]
This is a general problem on the Mac.  Somebody made a few changes on the rash assumption that clang/clang++ and gcc/g++ are interchangeable... and some assumptions about Python.

This has made an incompatible mess for a linux-like build environment (which the Mac use to be good at.)

I have OS 10.15.7 (Catalina)
XCode 12.4

Things that I have done so far to unwind this...

check `gcc --version` and `g++ --version` to see if the output mentions clang

delete the **symbolic link** and make a new **symbol link** of `g++` to:
/usr/local/bin/g++-10

`brew reinstall gcc`

Add this to your bash/zsch start up file:
`export ARCHFLAGS="-arch x86_64"`

The last part of the puzzle I'm now trying to figure out is how to deal with

`python-config --includes`

The problem is Python installed onto the mac has been built with clang (or clang++), which is why the clang (and incompatible) compile option gets put out which in my case:

-iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders
-iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers

-iwithsysroot is a flag for clang/clang++, but is not a flag for gcc/g++

If I run
`python`

I get:

```
Python 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
```

So, somehow I need to futz with which Python I have on my Mac, but I'm also having issues there...
