### ISSUE TITLE
如何支持c++依赖库版本控制

### ISSUE THREAD

**Issue by ChinaChenp** [chen3feng/blade-build#565]
比如我编译工程A，工程A依赖B/C/D，B/C/D又不能提前预编译，因为随时有人在改动，期望用A里面有版本能控制是否要编译B/C/D，这种功能能实现吗？

**Comment by WindLeeWT** [comment]
目前不支持

- 首先，A 依赖 B/C/D，那么编译 A 时必然需要 B/C/D

- 其次，B/C/D 不能预编译，那么必然是需要 B/C/D 的源代码，在编译 A 时，进行编译

那么问题转换为如何控制 B/C/D 的源代码版本，可以通过类似 git submodule 的方式进行控制，引用 B/C/D 源代码仓库的版本

blade 目前不支持类似 bazel 里的 http_repository 的方式，可以引入外部某个依赖的特定版本源代码，只能间接通过 git 等工具的方式引入

**Comment by ChinaChenp** [comment]
c++依赖包没有类似其他语言的管理机制，而且c++的编译就比较慢；比如idl这种，没法预编译，我们在想有没有更好的方式解决这个问题。

**Comment by chen3feng** [comment]
这个应该是代码管理工具的事情

**Comment by dandyhuang** [comment]
bazel 里的 http_repository 的方式感觉挺好用的，希望能支持一下
