### ISSUE TITLE
没有获取项目名、路径的内置变量

### ISSUE THREAD

**Issue by leeqx** [chen3feng/blade-build#566]
项目中依赖其他子项目时，blade 写的构建脚本，由于没有办法拿到当前项目的名称，实现的时候特别别扭。子项目的BUILD（submodule），路径问题导致构建失败

**Comment by WindLeeWT** [comment]
能否给出一个简单的例子？另外项目名指的啥，目录名？

**Comment by leeqx** [comment]
> 能否给出一个简单的例子？另外项目名指的啥，目录名？

比如我的项目名是projectA，我希望是能够在BUILD 文件中能通过一个内置的变量来获取到这个项目名称projectA。目前只发现有极少的内置变量比如FIRST_SRC

**Comment by yanyan33333** [comment]
@WindLeeWT @chen3feng 
这里能不能增加几个类似 $BUILD_DIR 的内置变量
1.当前BUILD所在的路径
2.BLADE_ROOT所在的路径
3.在build[32|64]_[release|debug]中，生前bin或者library的路径

现在的 $BUILD_DIR 变量是跟target相关的，就是说在gen_rule中表示build[32|64]_[release|debug]中的目录，在cc_library中表示BUILD所在的目录

**Comment by WindLeeWT** [comment]
提供这些变量的价值是什么？blade 本身提供了大量的预置规则(cc_\*, proto_library, java_\*, ...)用于日常的构建动作，开发者需要做的就是在 BUILD 文件中指定各个规则的名字和 `srcs`，`deps`等属性，`deps` 里统一使用 `//path/to:target` 来描述一个依赖的目标，自定义的动作可以通过 `gen_rule` 来实现，也可以在 blade 中通过新加 your_target.py 来实现，对于极少数的情况，可以在 BUILD 中写 python 代码和 import blade 来实现你的目的：

BUILD
```python
import os
from blade import build_manager as blade

source_path = blade.instance.get_current_source_path()  # 当前BUILD文件所在的路径
root = blade.instance.get_root_dir()  # BLADE_ROOT文件所在的路径
build_path = blade.instance.get_build_path()  # 当前的 build[32|64]_[release|debug]
# Other information could be obtained from src/blade/build_manager.py
```

btw, 目前只有 gen_rule 中存在内置变量($SRCS, OUTS, FIRST_SRC, FIRST_OUT, BUILD_DIR), cc_library 中没有内置变量，如果在一些属性中需要引用其他规则的输出，请参考 `$location 语法格式`

**Comment by yanyan33333** [comment]
主要原因是从原makefile项目迁移到blade的过程中发现原项目中有大量的引用头文件没有带上路径的，例如
`#include "common.h"`
按照blade的规则应该写成 
`#include "comm/common.h"`

虽然提供了fix-include-path.sh工具，但是还不能覆盖所有的情况，故我们写了一个makefile转BUILD的工具，在每个BUILD文件中cc_library中的export_incs带上当前BUILD和在build[32|64]_[release|debug]中的路径

目前的解决方案是，我们修改了源码
在gen_rule的cmd和cc_*的incs和export_incs增加了几个环境变量

$BASE_DIR 当前BUILD文件相对于BLADE_ROOT的相对路径 例如comm
$OUTPUT_DIR 当前BUILD文件所生成的文件的相对路径 例如 build64_release/comm
$ROOT_PATH BLADE_ROOT文件所在的绝对路径 例如/home/user/code

target.py
```python
self.root_path = self.blade.get_root_dir()
self.outs_dir = os.path.normpath(os.path.join(self.build_path, self.path))
```
gen_rule.py
```python
cmd = cmd.replace('$BASE_DIR', self.path)
cmd = cmd.replace('$OUTPUT_DIR', self.outs_dir)
cmd = cmd.replace('$ROOT_PATH', self.root_path)
```
虽然不是官方提倡的方案，但是项目文件太多不太可能逐一修改，这样算是一个折中的方案吧，对原文件几乎不需要修改^_^

**Comment by WindLeeWT** [comment]
对于长期维护的项目，建议还是按照规则做一次 BUILD/include 整理，看起来是花费了一些时间，实则为后面项目开发做好了基础，减少了 include 出错的一些奇怪问题

关于 include 这里有几点建议供参考：

  1. 一些 3rd 库，内部 include 头文件都是直接或相对 include，这种库无需调整 include 起始路径，比如 `a.h include b.h` `b.h include ../config.h`，gcc 搜寻头文件的规则支持寻找当前文件所在路径的 .h 文件

  2. 其他 3rd 库，比如 boost, protobuf，按需添加 incs/export_incs，组织的比较好的 3rd 库，基本上就是一两个根路径

  3. 自有代码，建议统一替换 include 从根开始

  4. 通常不需要 export incs build[32|64]_[release|debug]，是说有生成代码的规则？对于 protobuf，建议是调整 import 路径，这样就无需导出 build 路径了

**Comment by yanyan33333** [comment]
对于第4点，如果需要生成非protobuf或者是thrift的有代码，例如[tars](https://github.com/TarsCloud/Tars)(jce)格式的文件，代码会生成到 build[32|64]_[release|debug] 目录下，怎么样会方便一些呢？

**Comment by WindLeeWT** [comment]
内部有小部分服务还在使用 jce，版本相对于最新的 tars 可能旧一点，但做法是类似的，jce2cpp 支持 --dir 参数指定输出目录(默认生成到当前目录)，这里有一点小技巧，把 .h/.cpp 生成到 srcs 对应的 build 目录，从而其他的 .h/.cc 写 include 的时候也是从根开始，这样就和 protobuf 一致了：

//ad/search/proto/{BUILD, ad_search_service.jce}
BUILD
```python
gen_rule(
    name = 'ad_search_service_jce',
    srcs = 'ad_search_service.jce',
    outs = ['ad_search_service.h', 'ad_search_service.cpp'],
    cmd = 'thirdparty/jce/jce2cpp $SRCS --dir=`dirname $FIRST_OUT` --pdu',
)

cc_library(
    name = 'ad_search_service',
    srcs = 'ad_search_service.cpp',  # blade 自动探测 //ad/search/proto/ad_search_service.cpp 不存在
                                     # 则寻找 //blade-bin/ad/search/proto/ad_search_service.cpp
    deps = ':ad_search_service_jce',
)
```

其他 .h/.cc
```c++
#include "ad/search/proto/ad_search_service.h"
```

**Comment by yanyan33333** [comment]
是的，我们现在也是这样处理的，只不过#include 的时候没有修改成全路径
