### ISSUE TITLE
是否支持只包含头文件的target

### ISSUE THREAD

**Issue by yanyan33333** [chen3feng/blade-build#568]
有一些公共模块只包含.h文件，不包含.c或者.cpp文件，这时就不能使用cc_library生成.a或者.so的target，有没有方法可以支持只包含.h文件的target呢？

**Comment by chen3feng** [comment]
cc_library的srcs可以为空列表

HeroWong <notifications@github.com> 于2019年11月8日周五 下午5:23写道：

**Comment by yanyan33333** [comment]
好的，使用cc_library,把srcs配置为空列表就，export_incs配置为.h文件的目录就可以了
