### ISSUE TITLE
thirdparty里的protobuf在macos上不能用吗

### ISSUE THREAD

**Issue by formath** [chen3feng/blade-build#571]
https://github.com/chen3feng/thirdparty
另外，thirdparty还维护吗，protobuf没有3版本的
谢谢

**Comment by chen3feng** [comment]
我看一下

**Comment by HenryQin** [comment]
编译protobuf 直接报了 thirdparty/protobuf/BUILD:3: error: protobuf: Missing "hdrs" declaration. The public header files should be declared explicitly, if no public header file, set "hdrs" to empty (hdrs = [])
