### ISSUE TITLE
thrift不支持为单个library增加extra include paths

### ISSUE THREAD

**Issue by jiarongbupt** [chen3feng/blade-build#572]
比如当前目录路径为thirdparty/apache_arrow-2019-10-17/cpp/src/parquet
thrift文件中包含cpp_include "parquet/windows_compatibility.h"
需要指定编译路径为thirdparty/apache_arrow-2019-10-17/cpp/src
当前只能通过修改thrift_library_config来配置，会影响整个trunk

**Comment by chen3feng** [comment]
全局方式其实是不是更统一一些？
不过你这个issue其实是期望这些头文件能透传给依赖这个库的库？
其实有个更好的办法，
把 apache_arrow 用 BUILD 文件来描述
```python
cc_library(
    name = 'apache_arrow',
    export_incs = ['cpp/src'],  # export_incs 会透传给使用者
    ...
)
```
让你的 thrift 库去依赖这个库
```
    deps = [
        'thirdparty/apache_arrow-2019-10-17/:apache_arrow'
    ]
```
