### ISSUE TITLE
老版本升级到1.1.2的时候报错

### ISSUE THREAD

**Issue by ChinaChenp** [chen3feng/blade-build#573]
我一直用的是老版本，编译都没有问题，但是当我升级到1.1.2的时候，gen_rule编译的时候发现会报这种错误:
![image](https://user-images.githubusercontent.com/15309278/70497559-86221100-1b4e-11ea-8f57-ac6fe76beff5.png)
执行后目录下thrift相关的*.cpp和*.h都已经生成了；但是blade build的时候就会报上面的错误；老版本编译没有问题

生成的脚本如下：
![image](https://user-images.githubusercontent.com/15309278/70497528-668ae880-1b4e-11ea-8fce-e701fad8153f.png)

是新版本对gen_rule做了调整？

**Comment by WindLeeWT** [comment]
1. 新的 gen_rule 中 `cmd` 运行结束后会检查生成文件是否生成了 `ls outs`，就是截图1里的 ls 错误，可以 find 一下生成文件生成到那个目录下了

2. `outs` 里的路径默认是相对于当前源码的 build 目录，比如当前的 BUILD 目录是 //path/to/gen，则 outs 里的路径默认是相对于 //build64_release/path/to/gen，所以一般无需手动写出 $BUILD_DIR/.. 之类的，这里有个类似的[例子供参考](https://github.com/chen3feng/blade-build/issues/566#issuecomment-558903886)

3. 对于 thrift，有现成的 [thrift_library](https://github.com/chen3feng/blade-build/blob/master/src/blade/thrift_library.py)

**Comment by ChinaChenp** [comment]
我看了例子，还是没有解决问题；

- **我们生成的代码不能在默认路径，目前是生成在“位置1”，所以“outs”目录里面指定的也是和生成路径保持一致的“位置2”**

![image](https://user-images.githubusercontent.com/15309278/70522905-efb91400-1b7c-11ea-9599-d68eb9c31c9c.png)

所以问题是怎么指定去“位置2（位置1和位置2目录是一样的）”检查，而不要去默认路径检查？

- **其次我发现按上面的gen_rule规则，blade build的时候 发现查找的路径会重复，如下：**

![image](https://user-images.githubusercontent.com/15309278/70523054-28f18400-1b7d-11ea-985f-897c12c627d6.png)
出现了2次 “ddfp_thrift_protocol”

**Comment by WindLeeWT** [comment]
gen_rule 里处理 outs 的时候，是对于每个 out，当前 BUILD 文件路径 path，拼接路径 os.path.join(builddir, path, out)，所以你这里就是（假设 path 是 ddfp_thrift_proto）：
```python
>>> os.path.join('build64_release', 'ddfp_thrift_proto', 'build64_release/../ddfp_thrift_proto/ex/loc.cc')
'build64_release/ddfp_thrift_proto/build64_release/../ddfp_thrift_proto/ex/loc.cc'

```
可以把 outs 里的路径改为 '../ddfp_thrift_proto/ex/loc.cc'，其实直接写 'ex/loc.cc' 就行了，或者建议使用 thrift_library

**Comment by ChinaChenp** [comment]
假如build 根目录在 /build_root/下
我需要gen的BUILD在   /build_root/ddfp_thrift_proto/ 下面，生成的代码也要放到这个目录下
- 我们所有的头文件都依赖都指定到这个目录下
- 用thrift_library 方式不行，因为我们thrift -gen cpp 的时候指定的编译选项，比如增加 cpp::moveable_types, pure_enums 等，有特定的要求

下面这2种方式改动还是会找不到，改了其他路径问题依旧，而且发现找不到的时候好像会去默认路径找；
改法1  '../ddfp_thrift_proto/external/LocService.cc'
该法2  'external/LocService.cc'

正确的寻找路径
相对路径:  /build_root/build_release/ddfp_thrift_proto/../../ddfp_thrift_proto/external/
绝对路径:  /build_root/ddfp_thrift_proto/external/

我想法是里面处理相对路径有问题，按理说我以前的写法“位置2”是绝对路径，怎么也不会有问题，但是现在不支持绝对路径；

**Comment by WindLeeWT** [comment]
- 我们所有的头文件都依赖都指定到这个目录下
  我之前的那个例子其实有提到，默认会生成到 /build_root/build64_release/ddfp_thrift_proto/ 下，其他 .h 里 include 的时候还是 `#include "ddfp_thrift_proto/external/LocService.h"`，因为默认 blade 会添加 build64_release 到头文件搜索路径中，这样生成代码**不污染源码目录**，正好放到原 thrift 目录的镜像 build 目录，是推荐的使用方式

- 用thrift_library 方式不行，因为我们thrift -gen cpp 的时候指定的编译选项，比如增加 cpp::moveable_types, pure_enums 等，有特定的要求
  最近内部也有一些人提过，准备改一下这里，支持 thrift_library 级别的选项配置
