### ISSUE TITLE
How to add python code in build?

### ISSUE THREAD

**Issue by duduscript** [chen3feng/blade-build#574]
I want to run autoformat script in build, how to add python code run in build process when I type 'blade build ...'

**Comment by WindLeeWT** [comment]
There is no such thing in blade currently but alternatively you could write a shell wrapper `blade` which calls your autoformatting script before the actual building.
Another better approach is to integrate autoformat script/tool into your IDE/editor and be triggered automatically as soon as saving files.

**Comment by duduscript** [comment]
@WindLeeWT Thank you for your suggestions, our project is maintained by a team and we should make the format style for everyone is the same, maybe a shell script wrapper blade is the better choice.
