### ISSUE TITLE
老版本升级后挂掉，提示「Blade(error): Unknown target architecture  from gcc.」

### ISSUE THREAD

**Issue by Liam0205** [chen3feng/blade-build#575]
检查发现，使用 clang 时，会有此问题。因为执行 `llc --version` 返回值是 1 而非 0，于是代码 return 空，造成上面提示。

![image](https://user-images.githubusercontent.com/3348485/70787184-1ec3c580-1dc9-11ea-91e0-36dea3e061ca.png)

**Comment by Liam0205** [comment]
用 GCC 时，没有这个问题。我这边暂时用 GCC 绕过了；或者可以修改 `blade_platform.py` 里的内容，在使用 clang 时不检查 `llc --version` 的返回值，以便暂时绕过。

但我感觉这个不是 blade 的问题，是 clang 的问题。

**Comment by WindLeeWT** [comment]
不确定是不是 llvm 的版本问题，我之前测试 llvm8 和 9，`llc --version` 都可以正常运行

![image](https://user-images.githubusercontent.com/14238472/70791933-1c666900-1dd3-11ea-8ab1-ac6ff15d1100.png)

**Comment by Liam0205** [comment]
@WindLeeWT 
我觉得很可能是。因为我看了 llvm 的文档，`llc --version` 的返回值就应该是 0。感觉是系统上安装的版本有问题。

**Comment by chen3feng** [comment]
估计是
