### ISSUE TITLE
怎么去掉__FILE__中的路径？

### ISSUE THREAD

**Issue by seerhan** [chen3feng/blade-build#576]
blade是从root开始构建，源码中__FILE__经常替换为[base/system/net.cpp]之类的包含路径的值。

请问：如何才能将__FILE__值中，去掉路径，只包含net.cpp？

**Comment by WindLeeWT** [comment]
blade 目前不支持编译阶段调整输入文件路径 `base/system/net.cpp` -> `net.cpp`，可以考虑其他变通的方式：

1. 查看 gcc/clang 文档，编译器是否提供了类似的宏：

    \_\_BASE_FILE__
    This macro expands to the name of the main input file, in the form of a C string constant. This is the 
    source file that was specified on the command line of the preprocessor or C compiler.

2. 在处理 __FILE__ 的地方，例如日志库，统一将 full path 转换为 basename

**Comment by seerhan** [comment]
在makefile里，类似  -D__FILE__=$(nodir $abspath(file)) 。
期望在blade也能提供个类似函数。

否则，每次log都要下执行下basename()，感觉有点浪费。

**Comment by chen3feng** [comment]
感觉 gcc 的 __BASE_FILE__ 应该是最满足你要求的，可以改一下日志库。如果要考虑跨平台，basename 更好。覆盖编译器预定义宏问题更大。
