### ISSUE TITLE
blade build support Centos 8?

### ISSUE THREAD

**Issue by welsonzhang** [chen3feng/blade-build#577]
I build my projcet in Centos 8,  it report that:

```
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build64_release
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
scons: *** [build64_release/main/main] Error 1
scons: building terminated because of errors.
Blade(error): building failure.
Blade(error): failure
```
and I check that -lstdc++ is installing in my Centos 8 system.

but, it can build success in Centos 7 the same code. 

blade build support Centos 8?

**Comment by seerhan** [comment]
默认链接的是静态库。

**Comment by chen3feng** [comment]
参见 [FAQ](https://github.com/chen3feng/blade-build/blob/master/doc/zh_CN/FAQ.md#cannot-find--lstdc)
