### ISSUE TITLE
1.1.2 不支持Python 3.6，采用主干代码编译各种mix strings and bytes错误

### ISSUE THREAD

**Issue by tianmy** [chen3feng/blade-build#580]

**Comment by WindLeeWT** [comment]
之前 #534 做了一些兼容 py2/3 的修改，但是 python3.6+ 我没有测试过，内部还是在使用 2.7.x，str/unicode 这里是个麻烦的地方，我的想法是过一阵打个 tag 后就不再支持 2.7 了，集中改一次，后面就是只支持 3.6 了，@chen3feng 也看看这里

**Comment by chen3feng** [comment]
目前分支上有一个2to3，不过尚未测试完毕。将来是期望2/3兼容

**Comment by chen3feng** [comment]
Fixed in #631
