### ISSUE TITLE
import 部分包出现错误

### ISSUE THREAD

**Issue by sddi** [chen3feng/blade-build#581]
您好，想问下我在项目工程中采用blade build ...编译的时候，显示一些第三方库
import blade_util
ImportError: No module named blade_util
这个可以怎么统一解决一下呀？

**Comment by WindLeeWT** [comment]
blade 改了 package 结构
```python
from blade import blade_util
```

**Comment by sddi** [comment]
> blade 改了 package 结构
> 
> ```python
> from blade import blade_util
> ```

那岂不是所有的库都需要这么改一下？有没有更好的方案？

**Comment by chen3feng** [comment]
这些目前都是内部接口，blade尚未定义严格的开发API。可能只能跟着做修改了。
如果要兼容不同版本，可以用
```python
try:
    import blade
except:
    from blade import blade_util
```
兼容
