### ISSUE TITLE
如何在 prebuilt=true 的 library 中执行自定义编译规则？

### ISSUE THREAD

**Issue by JimChengLin** [chen3feng/blade-build#584]
我发现 Blade 几乎没有很轻松的方法来引入一个外部编译的库，比如 CMake，Makefile。

我唯一找到的可能文档是 gen_rule。**我成功使用 gen_rule 调用 CMake 生成了编译产物，但是却无法让 Blade 知道哪个编译产物要给使用者链接。**

于是我又尝试了 cc_library 并设置 prebuilt=true ，deps 添加 gen_rule target。但很奇怪的是如果有了 prebuilt=true，**deps 生效是晚于 Blade 找 prebuilt library 的。** Blade 会先报找不到对应的库，然后 deps 生效开始执行自定义编译规则。

这导致了很多非常滑稽的用法，比如大量的库都直接采用二进制发布，升级 GCC 变成了一个非常艰巨的任务。Blade 的编译功能就基本没了，实际上就是一个自动 git clone 工具。

我的 BUILD 文件如下

```
gen_rule(
    name="gen_mylib",
    outs="libmylib.a",
    cmd="./mylib/build.py",
)

cc_library(
    name="mylib",
    deps=":gen_mylib",
    export_incs=["include"],
    prebuilt=True,
)

```

build.py 会调用 CMake 在项目下的 lib 目录生成对应的 a 文件。

**Comment by WindLeeWT** [comment]
关于如何引入一个通过其他 build system 生成（Make/Cmake）的静态库到 blade 中，目前可能还是需要手动生成 + 提交二进制库 prebuilt=True 到代码库中。之前内部也有同事问过，当时的问题是如何把 go 生成的 .a 给 c++ 使用，也是尝试了 gen_rule + cc_library 类似的方式，我当时想了一下，觉得各种方式都有不足，有几点考虑

  1. blade 中各个规则之间的关系是**确定**的，也就是 cc_binary/cc_test <-- cc_library/proto_library <-- cc_library...，换句话说，cc_binary 能够 _理解_ cc_library 的输出并且在这条关系链上传递 `deps` 关系。好的，有一天突然改为了 cc_binary <-- gen_rule，gen_rule 可以生成任意文件(.h/.cc/.so/.a/.java/other unknown files)，cc_binary 可以去强制依赖这些输出产物来保证依赖关系，但是无法识别并利用这些文件去做**链接**，因为 cc_binary 只能理解 .a/.so 等 cc_library 的输出，现在没有去根据扩展名或其他标签的方式去告诉 cc_binary

  2. 假设 #1 中的方式能够支持，blade 就具备了编译功能吗？在我看来并不是，只是把其他 build system 的产物可以轻松的揉在一起，这样第三方库可以由 make/cmake/bazel/buck 生成，然后集成到一起，这么看来，blade 才是一个真正的 git clone 工具了

  3. 假设 #2 中的做法也是支持的，会有什么问题？

  - blade 无法识别**实际**的依赖关系，blade 中只能看到 `build.py`，build.py 里做了什么，某个 make/cmake 的源文件改了，blade 并不知道，全量和增量依赖关系没有了，某种意义上来说，基本等同于 prebuilt 库

  - blade里全局的 cc 编译选项/优化选项/宏等配置对于各个 gen_rule 生成的库不生效，这些编译配置被分散在各个 makefile/cmakelists 中，反而不利于编译器/编译语言标准等的升级

  - 由于采用了其他的 build system，重定义，重复代码会很多，比如某些底层库会有多份，甚至版本冲突

所以其实这并不是滑稽而是懒惰，最好的做法是做一次第三方库的改造，由 makefile/cmakelists/BUILD --> BUILD，诚然这有一定的工作量，如果有个类似 vcpkg 的软件仓库就好了，可以利用别人的改造工作成果。当然关于这个问题，也希望有更多的开发者能够给出更好的方案。

**Comment by JimChengLin** [comment]
感谢开发者的快速回复！我承认用 CMake 假装集成进了 Blade 和用 Blade 发布二进制都不是「最佳实践」。但为什么不能让使用者自己承担风险来控制编译链条呢？C++ 不就是这么设计的吗？我已经完全被锁死在 GCC 4.9.2 了。因为整个链路的库全是 GCC 4.9.2 编译的二进制。如果用 CMake，还可以设置 CXX CC，二进制完全无能为力了。

**Comment by WindLeeWT** [comment]
关于 GCC 升级，根据内部之前的实践，GCC 升级和 -std 的升级，都不影响使用原有的库，唯一需要注意的是 [ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)，

    If you get linker errors about undefined references to symbols that involve types 
    in the std::__cxx11 namespace or the tag [abi:cxx11] then it probably indicates 
    that you are trying to link together object files that were compiled with different
    values for the _GLIBCXX_USE_CXX11_ABI macro. This commonly happens when linking to
    a third-party library that was compiled with an older version of GCC. 
    If the third-party library cannot be rebuilt with the new ABI then you will need to
    recompile your code with the old ABI.
    

只要 ABI 保持不变，仍然可以兼容低版本 GCC 编译的库，比如从 GCC 4.4.6 --> GCC 4.9.4/-std=gnu++11 --> GCC 8.2/-std=gnu++17，依然可以使用原来 GCC 4.4.6（甚至 GCC 4.1）编译出的 .a

**Comment by JimChengLin** [comment]
解决方案：可以在 BUILD 文件中直接执行 Python 代码来提前编译绕开 prebuilt 的限制。

**Comment by chen3feng** [comment]
foreign_cc_library 分支进行了一定程度的支持
