### ISSUE TITLE
How to download test data when run 'blade test'?

### ISSUE THREAD

**Issue by duduscript** [chen3feng/blade-build#588]
I need to download data when I run unit test and this data is so big, I don't want to locate it in project as some users do not need to run unit test. 
I find the only way is to locate those data in project and define it in cc_test() dep, is there any method to solve this problem?

**Comment by GardianT** [comment]
save your test data in a git repo, add git submodule in your project. run ``git submodule --init --recursive`` before you run  ``blade test ...``.  will that be ok ?

**Comment by chen3feng** [comment]
It's the user's responsibility to prepare test data. you can use a `gen_rule` to download data and reference it in the testdata part
