### ISSUE TITLE
blade如何使用submodule引入的proto

### ISSUE THREAD

**Issue by GardianT** [chen3feng/blade-build#591]
比如git库是 myproto，同样使用blade编译，对外释放的proto library是 my_proto。 这个my_proto可能有两个文件参与，myprotoA.proto, myprotoB.proto  其中myprotoB.proto import了 myprotoA.proto

git submodule把这个文件夹引入进来，比如引入到src/proto下，那现在路径就是  src/proto/myproto

在cc_binary里引入deps为 src/proto/myproto:my_proto， 发现会报错。 myprotoB.pb.cc里，还是按照 myprotoA.proto这样去寻找函数的，类似 protobuf_AddDesc_myprotoA()  这样。但是实际上myprotoA 放出去的函数变成了  protobuf_AddDesc_src_proto_myproto_myprotoA()  这样。路径变化了。

在blade root中增加protobuf_path, protobuf_incs不能解决问题。想问下这个问题怎么解决

**Comment by GardianT** [comment]
另外问下proto_library支持prebuild发布吗？

还有文档里写的很疑惑。有一个文档是这么写的。

```
cc_library(
    name = 'secrity',
    prebuilt = True, # srcs 改为这个
    deps = [
        '//common/base/string:string',
        '//thirdparty/glog:glog',
    ]
)
```

这样发布prebuild库。 这里面连src都没指定么？src怎么写进去呢

**Comment by chen3feng** [comment]
一个proto在实际的编译中有两个路径，会导致不一致。
prebuilt的库因为是以二进制库的方式来发布的，不需要 srcs，库名是按约定来的。
