### ISSUE TITLE
从哪里可以获得比较全的thirdparty呢

### ISSUE THREAD

**Issue by sddi** [chen3feng/blade-build#592]
老师，看你repo的thirdparty都是很多年前的了，有没有近期最新的一些thirdparty呢？

**Comment by chen3feng** [comment]
列一下期望的列表？

**Comment by sddi** [comment]
@chen3feng  抱歉回复的这么晚，期望的一个列表有：
1. TensorFlow2.2， TensorFlow1.13还有其中涉及到的一些third_party
2. mpich
辛苦了~~~

**Comment by chen3feng** [comment]
嗯，打算之间支持外部构建工具产生的库

**Comment by sddi** [comment]
> 嗯，打算之间支持外部构建工具产生的库

那老师大概什么时候可以开发出来，能不能先支持下提出来的这2个呢？

**Comment by chen3feng** [comment]
这些都是 hazel 构建的，打通起来有些难度。在考虑能直接引用 bazel 构建的结果。

**Comment by sddi** [comment]
> 这些都是 bazel 构建的，打通起来有些难度。在考虑能直接引用 bazel 构建的结果。

好的。搞定之后会有通知吗？
