### ISSUE TITLE
blade 能是否有像cmake一样的set_source_files_properties的功能

### ISSUE THREAD

**Issue by yc1037642433** [chen3feng/blade-build#593]
最近在将项目的编译方式从cmake改为blade，但是CMakeLists.txt中通过set_source_files_properties为每个源文件添加了类似__FILE__这样的宏，不知道blade中有没有类似功能

**Comment by chen3feng** [comment]
能否拒个例子？谢谢

**Comment by yc1037642433** [comment]
CMakeLists.txt中有如下语句set_source_files_properties(${main.cpp} PROPERTIES COMPILE_DEFINITIONS "__FNAME__=\"net/${f}\"")
main.cpp中有：spdlog::log(spdlog::source_loc(__FNAME__, __LINE__, __FUNCTION__), spdlog::level::trace, fmt, ##__VA_ARGS__);

**Comment by yc1037642433** [comment]
CMakeLists.txt中有如下语句set_source_files_properties(main.cpp PROPERTIES COMPILE_DEFINITIONS "__FNAME__="net/${f}"")
main.cpp中有：spdlog::log(spdlog::source_loc(__FNAME__, __LINE__, __FUNCTION__), spdlog::level::trace, fmt, ##__VA_ARGS__);

**Comment by chen3feng** [comment]
是指perfile的编译选项吗？可以单独为这个文件建立一个cc_library或者cc_binary?

在 2020年4月5日星期日，yc1037642433 <notifications@github.com> 写道：

**Comment by yc1037642433** [comment]
其实是为每个源文件增加类似#define __FNAME__ "filename"这样的宏定义，我准备使用defs=['__FNAME__ "filename"',]为所有源文件定义一个相同的宏，但是不能通过编译，filename不能识别为一个字符串

**Comment by liubang** [comment]
> 其实是为每个源文件增加类似#define **FNAME** "filename"这样的宏定义，我准备使用defs=['**FNAME** "filename"',]为所有源文件定义一个相同的宏，但是不能通过编译，filename不能识别为一个字符串

你可以试试 `defs=['FNAME \\\"filename\\\"',]`

**Comment by yc1037642433** [comment]
> > 其实是为每个源文件增加类似#define **FNAME** "filename"这样的宏定义，我准备使用defs=['**FNAME** "filename"',]为所有源文件定义一个相同的宏，但是不能通过编译，filename不能识别为一个字符串
> 
> 你可以试试 `defs=['FNAME=\\\"filename\\\"',]`

谢谢，这种方法试了，可以增加一个宏定义
