### ISSUE TITLE
依赖版本冲突时候怎么指定版本

### ISSUE THREAD

**Issue by GardianT** [chen3feng/blade-build#594]
rt

**Comment by chen3feng** [comment]
具体是什么冲突？

**Comment by GardianT** [comment]
比如我编译了 lib A，lib A依赖了 thirdparty C的version1
编译了lib B ，lib B 依赖了 thirdparty C的version2
然后binary同时依赖了libA 和lib B，类似这样。

**Comment by chen3feng** [comment]
这个问题不是构建系统层面能解决的，类似[dll地狱/jar地狱](https://zh.wikipedia.org/wiki/DLL%E5%9C%B0%E7%8D%84)。
更高层面的解决方案：
- 统一依赖的版本
- 共用一个依赖
-
