### ISSUE TITLE
编译依赖的问题

### ISSUE THREAD

**Issue by AliceAndIron** [chen3feng/blade-build#684]
blade 如何配置解决编译依赖问题呢，解决
--start-group、--end-gourp
以及"-(" 、”-)“ 解决的问题

**Comment by chen3feng** [comment]
https://github.com/chen3feng/blade-build/blob/master/doc/zh_CN/build_rules/cc.md

link_all_symbols=True

hoho568 <notifications@github.com> 于2020年6月22日周一 下午8:00写道：
