### ISSUE TITLE
为什么不贡献到腾讯GitHub的账户中？

### ISSUE THREAD

**Issue by guodongxiaren** [chen3feng/blade-build#689]
这样这个项目关注度会更高吧。

**Comment by chen3feng** [comment]
因为这个项目是很早时通过CTO邮件批准开源的，那时候没有啥流程。
后来腾讯逐渐加强对外开源，有了规范的对外开源流程，我联系相关负责人想迁移过去，但是说要补代码扫描法务审核啥的，因为申请对外开源的项目太多，可能得排队等半年……，后来忙就没继续跟进了。后面在看吧。
