### ISSUE TITLE
README link direct to a non-free page

### ISSUE THREAD

**Issue by houqi** [chen3feng/blade-build#691]
**Describe the bug**
As title.

**To Reproduce**
click link: https://github.com/chen3feng/blade-build

![image](https://user-images.githubusercontent.com/1913192/89158256-6a1d2500-d5a0-11ea-88bd-411e4f9449ed.png)

腾讯公司“台风”云计算平台 is a link that direct to: http://wenku.it168.com/d_000434944.shtml

![image](https://user-images.githubusercontent.com/1913192/89158367-920c8880-d5a0-11ea-88bd-99db0f25bcf7.png)

**Expected behavior**
should read without pay.

**Error message**
You can read only part of the pdf.

**Comment by chen3feng** [comment]
thanks, will be updated

**Comment by chen3feng** [comment]
done
