### ISSUE TITLE
nodejs napi怎么使用blade构建

### ISSUE THREAD

**Issue by kimown** [chen3feng/blade-build#724]
c++项目使用blade构建，现在需要对nodejs封装成addon，napi官方案例都是使用cmake构建的

https://nodejs.org/api/n-api.html#n_api_build_tools

**Comment by chen3feng** [comment]
看起来是一个动态库，应该可以用 [cc_plugin](../blob/master/doc/zh_CN/build_rules/cc.md#toc10) 规则来构建。

**Comment by kimown** [comment]
> 看起来是一个动态库，应该可以用 [cc_plugin](../blob/master/doc/zh_CN/build_rules/cc.md#toc10) 规则来构建。

意思是使用blade构建静态库，然后再用cmake接入吗？

**Comment by chen3feng** [comment]
生成动态库，然后在 node 里引用
