### ISSUE TITLE
对于xxx.so.1这种构建好的库怎么引入？

### ISSUE THREAD

**Issue by LLLLF** [chen3feng/blade-build#742]
我需要引入一个构建好的.so，名字是xxx.so.1，在设置prebuilt=True之后name应该怎么设置？以及如何使blade默认执行打包规则？
（版本1.1.3）

**Comment by chen3feng** [comment]
name 随便设置啊，用 prebuilt 即可，这个 name 只是构建时候的标识。
打包值得是什么？package 吗？因为比较慢默认不执行，需要通过命令行启用，如果需要自动启用需要改源代码加新的配置项

**Comment by LLLLF** [comment]
如果我要引入一个库名字是 libabc.so.1，设置name为abc，设置prebuilt=True，编译会提示找不到libabc.so的库，不会自动寻找libabc.so.1

**Comment by chen3feng** [comment]
改名或者弄个 symbolic link 即可
