### ISSUE TITLE
Missing "hdrs" declaration.

### ISSUE THREAD

**Issue by sddi** [chen3feng/blade-build#743]
你好，想问下，最新的版本需要强制在BUILD里面指定hdrs吗？怎么兼容之前没有写这类配置的BUILD呢？

**Comment by chen3feng** [comment]
只检查了是否有 hdrs，hdrs 是否合理还没有检查。

存量代码通过配置忽略，配置可以自动生成，参见[文档](https://github.com/chen3feng/blade-build/blob/master/doc/zh_CN/build_rules/cc.md#%E4%BF%AE%E5%A4%8D-hdrs-%E5%BC%95%E5%8F%91%E7%9A%84%E4%BE%9D%E8%B5%96%E7%BC%BA%E5%A4%B1%E7%9A%84%E6%A3%80%E6%9F%A5%E9%97%AE%E9%A2%98)。
