### ISSUE TITLE
覆盖率插桩后gdb找不到__gcov_flush?

### ISSUE THREAD

**Issue by chenzb6677** [chen3feng/blade-build#744]
1、BLADE_ROOT全项目插桩：
cc_config(
cxxflags=['-std=c++14', '-fprofile-arcs', '-ftest-coverage'],
linkflags=['-fprofile-arcs', '-ftest-coverage'],
...
optimize = ['-O0'],
...
)

2、编译后strings查看gcda相关信息正常，比如：
.../build64_release/.../main.cpp.gcda

3、部署运行，gdb attach pid时，p __gcov_flush()提示异常：
(gdb) p __gcov_flush()
No symbol "__gcov_flush" in current context.

请问是什么原因？正确的插桩、编译参数是怎样的？

**Comment by chen3feng** [comment]
看起来没啥问题啊。nm 看看 __gcov_flush 是否链接了？

**Comment by chenzb6677** [comment]
> 看起来没啥问题啊。nm 看看 __gcov_flush 是否链接了？

nm的确是没有看到__gcov_flush关键字，strings能看到gcda
请问这个要怎么处理？

编译环境：
CentOS Linux release 7.6.1810
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5) //gcc 4.8.5 & devtoolset-7-gcc.x86_64 & devtoolset-7-gcc-c++.x86_64 & scl enable devtoolset-7 bash

**Comment by chenzb6677** [comment]
> 看起来没啥问题啊。nm 看看 __gcov_flush 是否链接了？

1.nm的确是没有看到__gcov_flush关键字，kill能生成gcda
2.linkflags加上-l:libgcov.a（gcc 4.8.5）选项，会报错undefined reference to `__gcov_exit'
请问怎么处理？

编译环境：
CentOS Linux release 7.6.1810
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5) //gcc 4.8.5 & devtoolset-7-gcc.x86_64 & devtoolset-7-gcc-c++.x86_64 & scl enable devtoolset-7 bash

**Comment by chen3feng** [comment]
`--coverage` 命令行参数即可

**Comment by gongshijun** [comment]
后面怎么解决呀，能给个详细介绍？

**Comment by gongshijun** [comment]
后面具体怎么解决的呀
