### ISSUE TITLE
高版本glibc编译的so，在低版本glibc的机器上加载失败

### ISSUE THREAD

**Issue by guodongxiaren** [chen3feng/blade-build#746]
**Describe the bug**
编译机glibc 是libstdc++.so.22 ，运行机器是libstdc++.so.19。会编译出可执行文件bin，和动态库so
运行的时候bin启动没问题。但是bin通过dlopen 打开so时报错：
```
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
```

这个有办法在不升级运行机器glibc的情况下运行吗？尝试过不使用dlopen，直接编译成一个bin的那些服务启动是ok的。这种bin+动态加载库的模式。bin ok，但是dlopen失败。

**To Reproduce**
2. Run '...'
3. See error

**Expected behavior**

**Error message**
If applicable, add an error message to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Ubuntu 18.4, MacOS 10.15.4]
 - Python version: [e.g. 2.7.17]
 - Version [Via `blade --version`]

**Additional context**

**Comment by chen3feng** [comment]
这个跟 blade 无关，编译可执行文件时可以静态链接 libgcc 和 libstdc++，但是 gcc 生产动态链接库时，libstdc++.so 只能动态链接。

可选解决方案：

- 使用静态链接的可执行文件而非动态库
- 把缺失的库发布到目标机器上
- 容器化部署
