### ISSUE TITLE
cc_library有办法只编译动态库，不编译静态库吗

### ISSUE THREAD

**Issue by guodongxiaren** [chen3feng/blade-build#747]
**Is your feature request related to a problem? Please describe.**
如此。想在部分目录的BUILD文件中控制只生成动态的库

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chen3feng** [comment]
这个需求的目的是什么呢？如果是期望生成被 `dlopen` 加载的库，用 `cc_plugin` 更合适，不会生成静态库。

**Comment by guodongxiaren** [comment]
> 这个需求的目的是什么呢？如果是期望生成被 `dlopen` 加载的库，用 `cc_plugin` 更合适，不会生成静态库。

cc_plugin编译会失败。当依赖protobuf的时候。编译报错：
```c
/usr/bin/ld: thirdparty/protobuf/lib64/libprotobuf.a(common.o): relocation R_X86_64_32S against `_ZTVN6google8protobuf7ClosureE' can not be used when making       a shared object; recompile with -fPIC
```
cc_library无问题

**Comment by chen3feng** [comment]
这个原因是没有统一用 -fPIC 编译，确保统一即可。
