### ISSUE TITLE
请问resource_library到底怎么用呢？

### ISSUE THREAD

**Issue by XyLearningProgramming** [chen3feng/blade-build#795]
**Is your feature request related to a problem? Please describe.**
```
StringPiece data = STATIC_RESOURCE(poppy_static_favicon_ico);
```
在文档中说明的这段代码，我既没找到STATIC_RESOURCE宏在哪里，也没有找到StringPiece的声明。还是想请教一下这里的用法？

**Describe the solution you'd like**
除了打包的方法以外，我觉得把.conf之类的配置文件拷贝一份到目录中也可以是一种解决办法。可是目前我感觉十分捉急，只能在bash里手动拷贝，十分不智能。如果有单纯的类似
```
copy_files(
name=;
srcs=;
)
```
也能达到resource_library的一大部分功能了，而且还跨语言。不知道有无类似的方法？

**Comment by XyLearningProgramming** [comment]
我来自问自答一下吧：
1 resource_library生成的头文件内有比较详细的说明，可以自己写宏或者直接读取生成头文件内的变量。对于文件内容来说返回的是`const char* const` 的类型；
2 conf之类的文档不适合作为static resource，因为不能改动的文件相当于是写死的；
3 conf文档的拷贝手写一行到脚本里也可，拷贝文档，即多个子项目/目录下用同一份conf的情况毕竟还是少的。

**Comment by chen3feng** [comment]
copy_files 可以用 `gen_rule`
