### ISSUE TITLE
Support deps on static/dynamic library explicitly

### ISSUE THREAD

**Issue by chen3feng** [chen3feng/blade-build#82]
cc_library(
    ...
    deps = '.../xxx.so',
    deps = '.../yyy.a',
)

**Comment by JianJI** [comment]
这个功能现在实现了吗？找了半天没有找到啊

怎么使用第三方的库呢，例如gflags之类

**Comment by yunlinchen** [comment]
如何使用第三方的动态库呢，类似prebuilt集成静态库进去

**Comment by chen3feng** [comment]
目前的实现支持：
prebuilt cc_library 同时有so和a时，根据链接模式自动选择。
只有一种时，识别并正确使用
