### ISSUE TITLE
Not allowed to depend on

### ISSUE THREAD

**Issue by sylarj** [chen3feng/blade-build#910]
error:  servant_header: Not allowed to depend on "//search_platform/thirdparty/tarscpp/util:util" because of its visibility,

my BUILD file path:
![image](https://user-images.githubusercontent.com/31975809/110079949-c3fafd00-7dc4-11eb-9f72-459b2e9e6fd4.png)

>

**Comment by chen3feng** [comment]
this is not a bug, it is a new feature

see

https://github.com/chen3feng/blade-build/blob/master/doc/en/upgrade-to-v2.md#target-visibility-control
