### ISSUE TITLE
关于BUILD文件中使用相对路径的问题

### ISSUE THREAD

**Issue by penii** [chen3feng/blade-build#914]
在编译他人编写的BUILD文件时，遇到文件中写着相对路径的情况
eg. ../g++/BUILD
会导致编译失败，请问是否为使用版本问题，或是参数配置问题

**Comment by chen3feng** [comment]
没看懂，具体一些？

**Comment by penii** [comment]
具体情况是这样的，我手里有一个使用blade编译的项目，在编译的过程中发生报错：
![3](https://user-images.githubusercontent.com/37393950/111066327-6f106280-84f9-11eb-934d-37993adc7376.png)
该问题所指向的文件内容为一段相对路径
![4](https://user-images.githubusercontent.com/37393950/111066357-90714e80-84f9-11eb-84e2-e184ea45468a.png)
但blade似乎无法识别这个相对路径并完成编译，下附编译的命令、报错的BUILD文件
![2](https://user-images.githubusercontent.com/37393950/111066392-bf87c000-84f9-11eb-91e2-714c01c9744c.png)
![5](https://user-images.githubusercontent.com/37393950/111066397-c282b080-84f9-11eb-8a57-fc64c28632bc.png)

**Comment by chen3feng** [comment]
这个看起来很像是本来应该是符号链接，但是从不支持符号链接的系统比如windows拉取的代码，文件内容就变成这样了。
