### ISSUE TITLE
在C++项目中，引入部分汇编代码

### ISSUE THREAD

**Issue by wjguo2002** [chen3feng/blade-build#916]
求助：
在C++项目中，引入部分汇编代码，需要编译

场景:在引入Tars框架时，有部分汇编代码，如下链接：
https://github.com/TarsCloud/TarsCpp/tree/29b0107ce979e974c05f28210b32b1ab4d781113/util/src/asm
下有部分汇编文件

帮忙看看，如何通过Blade将源代码引入，可以编译；
多谢谢谢。

**Comment by wjguo2002** [comment]
cc_library(
       name = "util_asm",
       srcs = [
              #'jump_x86_64_ms_pe_gas.asm',
              #'jump_x86_64_ms_pe_masm.asm',
              'jump_x86_64_sysv_elf_gas.S',
              'jump_x86_64_sysv_macho_gas.S',

              #'make_x86_64_ms_pe_gas.asm',
              #'make_x86_64_ms_pe_masm.asm',
              'make_x86_64_sysv_elf_gas.S',
              'make_x86_64_sysv_macho_gas.S',

              #'ontop_x86_64_ms_pe_gas.asm',
              #'ontop_x86_64_ms_pe_masm.asm',
              'ontop_x86_64_sysv_elf_gas.S',
              'ontop_x86_64_sysv_macho_gas.S',
              ],
       deps = [
              ],
       )

只用.S的文件，可以编译生成.o文件，但是.asm无法生成。

**Comment by chen3feng** [comment]
收到

**Comment by chen3feng** [comment]
asm看起来是intel语法，而且是windows上的。这么多汇编，得根据目标os和cpu来选择合适的进src，不能都放进去。

**Comment by wjguo2002** [comment]
多谢回复，仔细看了原来的cmake文件，针对这部分，确实是根据os和cpu等标志分开编辑，谢谢。
