### ISSUE TITLE
安装了oh-ny-zsh之后，编译会报错，提示Blade(error): File "//***/BUILD" does not exist

### ISSUE THREAD

**Issue by linhongxuncn** [chen3feng/blade-build#921]
**Describe the bug**
原来的项目，可以正常通过 blade build ... 进行编译
终端输出如下：
Blade(info): Loading config file "/***/blade/blade.conf"
Blade(info): Loading config file "/***/src/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(info): Loading done.
Blade(info): Analyzing dependency graph...
Blade(info): Analyzing done.
Blade(info): Generating backend build code...

但是安装oh-my-zsh之后，使用 blade build ... 编译的时候，会提示 
终端输出如下：
"
Blade(info): Loading config file "/***/blade/blade.conf"
Blade(info): Loading config file "/***/src/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(error): File "//app/server/BUILD" does not exist
Blade(info): Loading done.
Blade(error): There are 1 errors in the load stage
Blade(info): Cost time 0.183s
Blade(error): Failure
"

**Comment by chen3feng** [comment]
```console
Blade(info): Loading config file "//blade/blade.conf"
Blade(info): Loading config file "//src/BLADE_ROOT"
```

看起来不太正常啊，路径中有 `//`，正常情况应该是类似：

```console
Blade(info): Loading config file "/data1/code/main/thirdparty/blade/blade.conf"
Blade(info): Loading config file "/data1/code/main/BLADE_ROOT"
```

里面是绝对路径。

**Comment by linhongxuncn** [comment]
完整的报错是这样：
/data/code/main/app/pcc/service/cx # blade build ... --cloud                       
yadcc-blade: Enabled yadcc to speed up compilation.
Blade: Entering directory `/data/code/main'
Blade(info): Loading config file "/data/code/main/thirdparty/blade/blade.conf"
Blade(info): Loading config file "/data/code/main/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(error): File "//app/pcc/BUILD" does not exist
Blade(info): Loading done.
Blade(error): There are 1 errors in the load stage
Blade(info): Cost time 0.157s
Blade(error): Failure

**Comment by linhongxuncn** [comment]
> ```
> Blade(info): Loading config file "//blade/blade.conf"
> Blade(info): Loading config file "//src/BLADE_ROOT"
> ```
> 
> 看起来不太正常啊，路径中有 `//`，正常情况应该是类似：
> 
> ```
> Blade(info): Loading config file "/data1/code/main/thirdparty/blade/blade.conf"
> Blade(info): Loading config file "/data1/code/main/BLADE_ROOT"
> ```
> 
> 里面是绝对路径。

完整的报错是这样：
/data/code/main/app/pcc/service/cx # blade build ... --cloud
yadcc-blade: Enabled yadcc to speed up compilation.
Blade: Entering directory `/data/code/main'
Blade(info): Loading config file "/data/code/main/thirdparty/blade/blade.conf"
Blade(info): Loading config file "/data/code/main/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(error): File "//app/pcc/BUILD" does not exist
Blade(info): Loading done.
Blade(error): There are 1 errors in the load stage
Blade(info): Cost time 0.157s
Blade(error): Failure

**Comment by guodongxiaren** [comment]
这个我知道。因为zsh（或者说oh-my-zsh）里面 三个点 ... 是有特殊含义的，等价于 ../.. 也就是表示上上级目录。

`blade build ...` 就会变成，去上上级目录中去找BUILD文件。

我也遇到过这个问题。所以建议官方不要使用三个点

**Comment by chen3feng** [comment]
> 这个我知道。因为zsh（或者说oh-my-zsh）里面 三个点 ... 是有特殊含义的，等价于 ../.. 也就是表示上上级目录。
> 
> `blade build ...` 就会变成，去上上级目录中去找BUILD文件。
> 
> 我也遇到过这个问题。所以建议官方不要使用三个点

我也用zsh，不过没用omz而是用的zinit。

不用三个点比较难，blaze派生的构建工具（包括Google自己的bazel）都沿用了这一语法。我更新一下文档吧

**Comment by chen3feng** [comment]
经测试，写成 `./...` 就可以了，稍后我更新一下文档。
