### ISSUE TITLE
Error parsing `nvcc --version` output

### ISSUE THREAD

**Issue by MagiaSN** [chen3feng/blade-build#932]
Hi, it seems you have fixed a similar issue in #931, could you fix this too?

https://github.com/chen3feng/blade-build/blob/770c66c72b36028ccb48f11d346b75859aa152ba/src/blade/toolchain.py#L182

**Comment by chen3feng** [comment]
thanks，fixing

**Comment by chen3feng** [comment]
Resolved in #933
