### ISSUE TITLE
mac: awk: nonterminated character class ^\.+ [^

### ISSUE THREAD

**Issue by atlantidewang** [chen3feng/blade-build#936]
mac:
FAILED: build64_release/thirdparty/gtest/gtest.objs/gtest.cc.o
\export LC_ALL=C; set -o pipefail; g++ -o build64_release/thirdparty/gtest/gtest.objs/gtest.cc.o -MMD -MF build64_release/thirdparty/gtest/gtest.objs/gtest.cc.o.d -c -fPIC  -DHAVE_CONFIG_H -D_GLIBCXX_USE_CXX11_ABI=0 -pipe -fno-omit-frame-pointer -g -DNDEBUG -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O2 -Wno-invalid-offsetof -Wnon-virtual-dtor -Woverloaded-virtual -Wvla -Werror=conversion-null -Werror=non-virtual-dtor -Werror=overloaded-virtual -Werror=reorder -Werror=vla -Wall -Wextra -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-missing-field-initializers -Wendif-labels -Wfloat-equal -Wformat=2 -Wframe-larger-than=69632 -Wmissing-include-dirs -Wpointer-arith -Wwrite-strings -Werror=char-subscripts -Werror=comments -Werror=empty-body -Werror=endif-labels -Werror=format -Werror=format-nonliteral -Werror=missing-include-dirs -Werror=overflow -Werror=parentheses -Werror=return-type -Werror=sequence-point -Werror=sign-compare -Werror=switch -Werror=type-limits -Werror=uninitialized -Werror=unused-label -Werror=unused-result -Werror=unused-value -Werror=unused-variable -Werror=write-strings  -I. -Ibuild64_release  thirdparty/gtest/gtest.cc -H 2>&1 | awk '/Multiple include guards may be useful for:/ {stop=1} /^\.+ [^/]/ { print $0} !/^\.+ / && !stop {print $0 > "/dev/stderr"}' > build64_release/thirdparty/gtest/gtest.objs/gtest.cc.o.H
awk: nonterminated character class ^\.+ [^

**Comment by chen3feng** [comment]
confirmed, thanks
