### ISSUE TITLE
have to run “blade test -j xx  dir_of_project/... ”  at least twice

### ISSUE THREAD

**Issue by kuafu-run** [chen3feng/blade-build#941]
**Describe the bug**
cmd:  blade test -j xx  dir_of_project/...
v2.0-beta2 not work once, need to run again. but v1.1.1 works fine.

**To Reproduce**
1. Go to 'dir_of_slution'
2. Run 'blade test -j xx  dir_of_project/...'
3. See error

**Expected behavior**
all test case should pass as does with  blade v1.1.1

**Error message**
some test cases (randomyl) will fail.
 
**System (please complete the following information):**
 - OS: [centos 7  48 cores ]
 - Python version: [e.g. 2.7.5]
 - Version [v2.0-beta2]

**Additional context**
my c++ project contains 7000+ compilation units and 170+ test cases most of which have multi-threaded behavior，and with  blade v1.1.1， the blade test works fine yet slowly， so i upgraded blade to V2 and chose v2.0-beta2，ran the cmd 'blade test -j xx  dir_of_project/...' as with blade v1.1.1，  yet  all cases would not pass the first time， and after i ran the cmd again，the unrepaired cases passed。

**Comment by chen3feng** [comment]
Can you show some detailed error messages of the first test? Maybe some test data file dependencies are not handled correctly?

**Comment by chen3feng** [comment]
Blade 2 runs tests concurrency automaticcally. Try add `-t1` when you use blade 2.

**Comment by kuafu-run** [comment]
yeah，it works！thank you very much！！！
