### ISSUE TITLE
example/cuda编译错误

### ISSUE THREAD

**Issue by bppan** [chen3feng/blade-build#952]
cd example/cuda
blade build :template

Blade(info): Loading BUILD files...
cuda/BUILD:10: error: template: Invalid source file name: "template.cu", must ends with ['s', 'c', 'cxx', 'cc', 'cp', 'c++', 'asm', 'C', 'S', 'cpp', 'CPP']
cuda/BUILD:16: error: cu_test: Invalid source file name: "cu_test.cu", must ends with ['s', 'c', 'cxx', 'cc', 'cp', 'c++', 'asm', 'C', 'S', 'cpp', 'CPP']
Blade(info): Loading done.
Blade(error): There are 2 errors in the load stage
Blade(info): Cost time 0.0376s
Blade(error): Failure

cu_binary的srcs是.cu报错了

**Comment by chen3feng** [comment]
confirmed, thanks

**Comment by chen3feng** [comment]
> 

yes, to be added later.
