### ISSUE TITLE
compilation error message is not print to stdout with distcc on

### ISSUE THREAD

**Issue by kuafu-run** [chen3feng/blade-build#956]
**Describe the bug**

**To Reproduce**
2. Run '...'
3. See error

**Expected behavior**
I have some problematic C++ code during building，once faild only to see 
FAILED: xxxxxxxxxxx.o
if anything，i would like to see the error message.

**Error message**
If applicable, add an error message to help explain your problem.

**System (please complete the following information):**
 - OS: [centos 7.4]
 - Python version: [e.g. 2.7.5]
 - Version [ blade-build-2.0-beta2 ]

**Additional context**

**Comment by chen3feng** [comment]
Can you provide a minimal reproducible set of code?

**Comment by kuafu-run** [comment]
my machine is centos 7.6 , gcc 4.8.5

[bug_demo.tar.gz](https://github.com/chen3feng/blade-build/files/7075063/bug_demo.tar.gz)
unpress the tar.gz file and run ./blade2 build demo/...

**i wish i could see the error msg like this:**

demo/demo.cpp: In function 'int Add(int, int)':
demo/demo.cpp:6:3: error: 'abcde' was not declared in this scope
   abcde;
   ^
demo/demo.cpp:7:1: error: no return statement in function returning non-void [-Werror=return-type]
 }
 ^
**but didn't**

**Comment by chen3feng** [comment]
Thanks, to be confirmed.

**Comment by chen3feng** [comment]
Maybe because distcc can't handle the stderr of compilation correctly when the `-H` option is used.

try upgrade distcc to the latest version?
