### ISSUE TITLE
问题：请问c++项目如何用blade使用pybind11编译成so文件供python调用

### ISSUE THREAD

**Issue by mayinghan** [chen3feng/blade-build#968]
c++项目很复杂，有很多依赖，目前线上是用blade编译的，有没有办法用blade和pybind11编译成一个本地版的so文件供python调用

**Comment by chen3feng** [comment]
生成 [cc_plugin](https://github.com/chen3feng/blade-build/blob/master/doc/zh_CN/build_rules/cc.md#toc10)。
