### ISSUE TITLE
Error: Target not exist, load_build_files.py may have bug

### ISSUE THREAD

**Issue by DataTerminatorX** [chen3feng/blade-build#976]
**Describe the bug**
cd `blade-build/example/quick-start`
run `blade build`, no bug
But run `blade build :say`, report error as below
![image](https://user-images.githubusercontent.com/12929606/151310936-09ad3ab8-aeb6-4091-9780-ace3fec8551e.png)

**My Debugging**
I found the error msg comes from `line 561` of `blade-build/src/blade/load_build_files.py`
![image](https://user-images.githubusercontent.com/12929606/151311440-577b9c02-aabf-4ba2-a6bf-0b02facab0d6.png)

I added `print(target_id)` and `print(target_database)` to debug. I found that when run `blade build`, the `target_id` is correct
![image](https://user-images.githubusercontent.com/12929606/151311857-f609c87e-1d68-43fa-8dd6-7fb6b27c7365.png)

but when run `blade build :say`, the `target_id` is wrong, which contains a redundant `.`
![image](https://user-images.githubusercontent.com/12929606/151312010-5b474643-03cd-4599-aca4-90fa56f9d4de.png)

**System (please complete the following information):**
 - OS: CentOS 7
 - Python version: 3.6.9
 - Version: (developing, unversioned) commit ID: 5be026337757cd50ddfb527cad1272ffea7051cc

**Comment by chen3feng** [comment]
Thank you, I will fix this issue recently.
