### ISSUE TITLE
C++覆盖率统计，使用lcov生成报告后丢失很多文件的数据统计

### ISSUE THREAD

**Issue by shanys** [chen3feng/blade-build#986]
**问题描述**
命令为：
`blade test ... -j8 -p release --full-test --gcov`

**构建选项为**
`Namespace(args=[], cache_dir=None, cache_size=2147483648, color='auto', command='test', fulltest=True, gcov=True, generate_dynamic=False, generate_java=False, generate_php=False, gprof=False, jobs=8, keep_going=False, m='64', no_debug_info=False, no_test=False, profile='release', scons_only=False, show_details=True, test_jobs=1, testargs=None, verbose=False)
['-m64', '-mcx16', '-pipe', '-g', '-DNDEBUG', '-D_FILE_OFFSET_BITS=64', '-D__STDC_CONSTANT_MACROS', '-D__STDC_FORMAT_MACROS', '-D__STDC_LIMIT_MACROS', '--coverage', '-fprofile-arcs', '-ftest-coverage']
`

**代码总行数**
<img width="128" alt="image" src="https://user-images.githubusercontent.com/7547479/165549464-f3333d83-03bf-4d8f-a20f-7e0d9f51a79e.png">

**覆盖率统计数据**
<img width="442" alt="image" src="https://user-images.githubusercontent.com/7547479/165549588-cd2346be-25bb-4d25-93e5-6e52badaabe5.png">

会是插桩问题还是统计问题？

**Comment by chen3feng** [comment]
是不是lcov的问题？时间久了，先关闭了。如果有需要可以重新打开。
