### ISSUE TITLE
编译错误信息不能彩色高亮显示的问题

### ISSUE THREAD

**Issue by zengkui** [chen3feng/blade-build#992]
**Describe the bug**
编译错误信息没有高亮显示的问题，输出信息截图如下：
![image](https://user-images.githubusercontent.com/1586033/182516374-c454dd85-8297-4a50-bf40-dc0fc6ad5faa.png)

**To Reproduce**

**Expected behavior**
希望报错的行能高亮显示

**Error message**

**System (please complete the following information):**
 - OS:  centos
 - Python version:  2.7.5
 - Version  blade (developing, unversioned)

**Additional context**

**Comment by chen3feng** [comment]
gcc版本过低？由于高版本gcc自带关键词高亮，现在blade默认不全行高亮错误信息了。

**Comment by zengkui** [comment]
> gcc版本过低？由于高版本gcc自带关键词高亮，现在blade默认不全行高亮错误信息了。

谢谢回复 。 
gcc 是8.3.1 这个版本应该够了？

**Comment by chen3feng** [comment]
我再确认一下啊
